### ISSUE TITLE
port higher-order Ramda functions which accept variadic functions

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#102]
In Ramda we're slowly replacing variadic functions with fixed-arity functions. I'm very much in favour of this. I'd like to go a step further in Sanctuary by fixing the arities of function *arguments*. [`R.both`][1], for example, has type `(** -> Boolean) -> (** -> Boolean) -> (** -> Boolean)`, where `**` represents zero or more arguments. I'd like to provide a `both` function in Sanctuary which is less flexible but which handles the common case with a simpler type, `(a -> Boolean) -> (a -> Boolean) -> a -> Boolean`.

The following is a list of such functions I'd like Sanctuary to provide (which I'll update it if turns out not to be exhaustive).

  - `both :: (a -> Boolean) -> (a -> Boolean) -> a -> Boolean`
  - `either :: (a -> Boolean) -> (a -> Boolean) -> a -> Boolean`
  - `anyPass :: [a -> Boolean] -> a -> Boolean`
  - `allPass :: [a -> Boolean] -> a -> Boolean`
  - `complement :: (a -> Boolean) -> a -> Boolean`
  - `ifElse :: (a -> Boolean) -> (a -> b) -> (a -> b) -> a -> b`
  - `converge :: (b -> c -> d) -> (a -> b) -> (a -> c) -> a -> d`
  - `flip :: (a -> b -> c) -> b -> a -> c`

This approach was briefly discussed in ramda/ramda#1395.

[1]: http://ramdajs.com/docs/#both

**Comment by svozza** [comment]
If no one is working on this I can grab `both`, `either` and `complement`?

**Comment by davidchambers** [comment]
Please do, @svozza. :)

**Comment by svozza** [comment]
Quick question, do we want to do the non-short circuiting version using `lift`?

**Comment by davidchambers** [comment]
I think we should short-circuit. It's likely Ramda will do the same.

**Comment by svozza** [comment]
Should I just wrap the relevant Ramda functions because we're still on v0.17 or will I reimplement them from scratch?

**Comment by davidchambers** [comment]
It would be clearer to implement them from scratch. This will also simplify the process of upgrading to Ramda v0.18.x.

**Comment by svozza** [comment]
What will we do about `either` given that it shares a name with a function currently in Sanctuary.

**Comment by davidchambers** [comment]
Yikes! That's a terrific question. `and` and `or` already exist as well. We should not merge #110 until we resolve this conundrum.

**Comment by davidchambers** [comment]
Perhaps what we actually want are fixed-arity versions of [`R.lift`][1]: `S.lift`, `S.lift2`, and `S.lift3`. This would allow `S.lift2(S.and)` and `S.lift2(S.or)` to function as `both` and `either` respectively.

/cc @benperez


[1]: http://ramdajs.com/docs/#lift

**Comment by svozza** [comment]
I've always thought `S.either` could be named better but having an `either` function not related to the `Either` type could be confusing.

**Comment by davidchambers** [comment]
@svozza, do you think the `S.lift{,2,3}` option is worth exploring?

**Comment by svozza** [comment]
So do we mean, not provide functions like `S.both` and `S.either` and just let people compose the `lift2` or `lift3` versions instead? As long as we don't mind losing the short-circuiting then yeah that could definitely work. Btw, how deep do we want the type checking on this stuff to go? Like do we want to create a pseudotype that checks that the function that's passed in in unary and the argument is of the correct type?

**Comment by davidchambers** [comment]
> So do we mean, not provide functions like `S.both` and `S.either` and just let people compose the `lift2` or `lift3` versions instead?

Yes, that's what I have in mind.

> Btw, how deep do we want the type checking on this stuff to go? E.g., do we want to create a pseudotype that checks that the function that's passed in is unary and the argument is of the correct type?

I'm working on a more ambitious pull request to replace plaid/sanctuary-def#1. It will allow one to specify the `a` in `[a]`, `Maybe a`, `Either a b`, etc. Even in this experimental branch, though, I treat a function's type as `Function` rather than `Function a b` (i.e. `a -> b`). I don't see how we'd determine a function's input and output types. We could check arity, but I'm not sure this is a good idea.

**Comment by svozza** [comment]
Yeah,  I agree I can't see how you could reliably do that and checking the arity would mean any variadic  function would automatically fail unless it wrapped in something like `R.arity`. That's a lot to expect from a user. 

Regarding the first suggestion, I think go for it, it's far more in the spirit of Sanctuary than ramda. Maybe use `or` and `and` in the doc examples to give people a nudge.

**Comment by davidchambers** [comment]
> Maybe use `or` and `and` in the doc examples to give people a nudge.

Good idea. We could even include `lift` examples in the `and` and `or` sections so people looking to logically combine functions will discover `lift(and)` and `lift(or)`. :)

**Comment by benperez** [comment]
@davidchambers :+1: for `S.lift`, `S.lift2`, `S.lift3` and friends

**Comment by davidchambers** [comment]
Thanks to contributions from @svozza and @benperez, we now have access to all these functions!

```javascript
//    both :: (a -> Boolean) -> (a -> Boolean) -> a -> Boolean
const both = S.lift2(S.and);

//    either :: (a -> Boolean) -> (a -> Boolean) -> a -> Boolean
const either = S.lift2(S.or);

//    anyPass :: [a -> Boolean] -> a -> Boolean
const anyPass = S.anyPass;

//    allPass :: [a -> Boolean] -> a -> Boolean
const allPass = S.allPass;

//    complement :: (a -> Boolean) -> a -> Boolean
const complement = S.lift(S.not);

//    ifElse :: (a -> Boolean) -> (a -> b) -> (a -> b) -> a -> b
const ifElse = S.ifElse;

//    converge :: (b -> c -> d) -> (a -> b) -> (a -> c) -> a -> d
const converge = S.lift2;

//    flip :: (a -> b -> c) -> b -> a -> c
const flip = S.flip;
```

**Comment by benperez** [comment]
:cake:
