### ISSUE TITLE
Can't Add Additional sanctuary-def Types To Env

### ISSUE THREAD

**Issue by svozza** [plaid/sanctuary#132]
I started work on the maths functions listed in #127 but have encountered some really strange behaviour. The very act of including `$.FiniteNumber` in `$.env` causes a bunch of tests to fail. They all involve functions that have a dependency on type classes in their definition. Here are some of the errors:

>TypeError: ‘Either#concat’ requires ‘a’ to implement Semigroup; Number and Integer and FiniteNumber do not

>TypeError: ‘xor’ requires ‘a’ to implement Alternative and Monoid; (Either ??? Number) and (Either ??? Integer) and (Either ??? FiniteNumber) do not

>TypeError: ‘xor’ requires ‘a’ to implement Alternative and Monoid; Number and Integer and FiniteNumber do not

Etc...

I'm guessing there's something going on with the definition of Sanctuary's `Semigroup` and `Alternative` types and is related to plaid/sanctuary-def/pull/16

**Comment by davidchambers** [comment]
Could it simply require updating the expected error messages to mention `FiniteNumber`?

**Comment by svozza** [comment]
Ah yes indeed. Although simply updating the error messages required changing 22 tests!
