### ISSUE TITLE
Consider using Symbol instead of instanceof

### ISSUE THREAD

**Issue by benperez** [plaid/sanctuary#14]
Currently you can't compare two instances of `Maybe` from different versions of `Sanctuary`. If Sanctuary registers a Symbol for each type in the global symbol registry at require time then these symbols could be compared across different version numbers.

**Comment by davidchambers** [comment]
I'm not sure this is a good idea. Currently if `x instanceof S.Just` evaluates true the behaviour of `x` is guaranteed. If we switch to an looser approach we won't know whether `x` has certain methods so may end up using feature detection:

```javascript
if (S.isJust(x) && typeof x.foo === 'function') {  // foo method was added in v0.8.0
  ...
} else {
  ...
}
```

This doesn't seem like an improvement.

**Comment by benperez** [comment]
Your criticism is definitely valid, you'll never be able to assume a given object has the same methods implemented. I guess the goal of using symbols would be that you could at least assume that you can always tell if something is an instance of something else. If that's the only thing you can guarantee though then this may not be worth it.

**Comment by davidchambers** [comment]
Closing as this approach would solve one problem but create another.
