### ISSUE TITLE
Even safer parseJson

### ISSUE THREAD

**Issue by Avaq** [plaid/sanctuary#150]
> `parseJson(Array, '{}') -> Nothing()`

I'm very fond of the `get` and `gets` style of type validation, because it forces you to do it. It would've already saved me on multiple occasions if `parseJson` (or any `x -> Any` function for that matter) had this built-in, because after doing a "safe" JSON parse, it doesn't always occur to me the return value may still be of an unwanted type.

An alternative is to extract this behaviour out to its own function, which is used solely for type validation:

```js
validate :: TypeRep -> a -> Maybe a

const parseJsonArray = compose(chain(validate(Array)), parseJson);
```

I think this second solution is more elegant in terms of modularity but it lacks the safety that comes from forcing you to do the type validation.

Side note: `TypeRep` [may be changed to a predicate](https://github.com/plaid/sanctuary/issues/149), but the idea remains the same.

**Comment by Avaq** [comment]
:information_source: I've started work on this.

**Comment by davidchambers** [comment]
I love the idea of being able to do this:

```javascript
> S.parseJson($.Array($.Number).test, 'XXX')
Nothing()

> S.parseJson($.Array($.Number).test, '["foo","bar","baz"]')
Nothing()

> S.parseJson($.Array($.Number).test, '[1,2,3]')
Just([1, 2, 3])
```

If we're to do this, we should address #149 as well. :)

**Comment by Avaq** [comment]
> If we're to do this, we should address #149 as well

It's my intent. But since the two issues have been collecting dust I figured I'd get at the low hanging fruit first. I'll implement it using `TypeRep`, it can then be merged and it would clear the way for the type checking overhaul, which would then also affect `parseJson`.
