### ISSUE TITLE
Return Nothing() If The Object passed To Get() Is Null

### ISSUE THREAD

**Issue by svozza** [plaid/sanctuary#16]
Would it be reasonable for `get` to have the above behaviour? I'd like to use this function as the 'gateway' for converting the values in a function pipeline to `Maybe`s. Currently I'm a querying a datasource using `highland` for some JSON that may return `null`. At the moment I do this:

```javascript
var _ = require('highland');
var R = require('ramda');
var S = require('sanctuary');

_(datasource)
     .map(R.compose(R.chain(S.get('b')), R.chain(S.get('a')), S.toMaybe))
     .reject(S.Nothing().equals)
```

It would be nice not to have to do that initial map with `toMaybe` and the subsequent call to R.chain so it would look like this:

```javascript
_(datasource)
     .map(R.compose(R.chain(S.get('b')), S.get('a')))
     .reject(S.Nothing().equals)
```
Or even nicer once v0.5.0 of Sanctuary drops:

```javascript
_(datasource)
     .map(S.gets(['a', 'b']))
     .reject(S.Nothing().equals)
```

**Comment by davidchambers** [comment]
I was excited to see this issue, @svozza. I had not realized that Sanctuary is being used outside a handful of Plaid projects. :)

I know of [Highland][1] but have never used it. Nonetheless, I believe I understand your problem.

In general—and *especially* in the case of Sanctuary—I believe functions should be strict about their inputs. Code written with Sanctuary should deal with `null` only where there is contact with foreign functions which return nullable values.

If we accept that it is the caller's responsibility to provide appropriate arguments to a function, we must first filter invalid values:

```javascript
_(datasource)
     .reject(R.isNil)
     .map(S.gets(['a', 'b']))
     .filter(R.is(S.Just))
```

I assume you're operating on a stream, but for the sake of comparison here's how I might write this were `datasource` an array:

```javascript
// transform :: [Object?] -> [Maybe *]
var transform = R.into([],
                       R.compose(R.reject(R.isNil),
                                 R.map(S.gets(['a', 'b'])),
                                 R.filter(R.is(S.Just))));
```

I'm interested in hearing from @buzzdecafe and @CrossEye. The question is whether it is the caller's responsibility to provide appropriate values or whether certain functions should be more forgiving. Certain Ramda functions treat `null`/`undefined` as an empty object. Currently Sanctuary takes a stricter stance.


[1]: http://highlandjs.org/

**Comment by svozza** [comment]
It's funny, in my first draft of this I did exactly as you do in your example and filtered with `R.isNil` but wasn't sure if that was the right thing to do. The reasoning behind my changing it was that I thought it was best to get the data wrapped in a `Maybe` as soon as possible to prevent errors. I'm quite new to using these monadic types so I'm learning as I go; I like the idea of just being able to make the code `null`-safe with a single function call but I understand your rationale regarding sanitising the data before passing it to Sanctuary. 

I'm currently refactoring a small section of our application where we have had persistent problems with `null` and `undefined` values. The `gets` function is going to very useful when it gets released, it'll definitely make it easier for me to sell this approach in general.

**Comment by buzzdecafe** [comment]
> It would be nice not to have to do that initial map with `toMaybe`

I think either of the two approaches (viz. `toMaybe` or `isNil`) is ok, but i don't think `map` et al. should null-check and wrap in an ADT.

off topic a bit: i am a fan of highland, and i'd love to ensure seamless integration with highland streams in ramda. maybe we can discuss elsewhere.

**Comment by svozza** [comment]
Yes, definitely. Do you want me to open an issue on the Highland project or would you rather do it on the Ramda page or even in Gitter?

**Comment by buzzdecafe** [comment]
any of the above is fine, or ping me via email. fwiw i imagined it as more of a ramda issue, for us to make sure we can consume highland streams point-free. 

ok, @davidchambers i'm sorry for hijacking this thread. back on topic now ...

**Comment by svozza** [comment]
Yeah. I'll open an issue on Ramda and call in some of the other Highland contributors who know the code much better than I do.

**Comment by CrossEye** [comment]
> I was excited to see this issue, @svozza. I had not realized that Sanctuary is being used outside a handful of Plaid projects. 

Watch out.  That's what happened to @buzzdecafe and me too with Ramda.  A year later, there are 1600+ commits from 62 different contributors, 31 open issues and 9 unresolved pull requests out of over a thousand total issues/PRs raised!  It's a fun ride, but a little scary too!  :smile:

> The question is whether it is the caller's responsibility to provide appropriate values or whether certain functions should be more forgiving. Certain Ramda functions treat null/undefined as an empty object. Currently Sanctuary takes a stricter stance.

I'm quite happy with this breakdown.  Ramda pushes things a fair way towards stronger typing of functions, but makes some pragmatic compromises familiar to Javascript developers.  Sanctuary pushes a little closer to languages like ML and Haskell.  Since they can play well together, a user can decide which level is appropriate for herself.

**Comment by davidchambers** [comment]
Thanks for your feedback, folks. Let's preserve the requirement that the second argument to `S.get{,s}` must not be null/undefined.

**Comment by svozza** [comment]
Sounds good. Thanks guys.
