### ISSUE TITLE
Proposal to add S.random

### ISSUE THREAD

**Issue by Risto-Stevcev** [plaid/sanctuary#162]
Would you be interested in adding a helper function for a random number generator, `S.random`?

`Math.random` is limited in that you can't specify a range (it's `[0, 1)`), which is why Lodash and Underscore have their own implementation. It would be nice to have something like this in the library.

**Comment by svozza** [comment]
Have you given any thought to how we can keep this function pure? Perhaps by accepting and returning a seed value for the next number.

**Comment by Risto-Stevcev** [comment]
Yeah, a seed sounds like a good idea. It would also be nice is implementing `newStdGen` could include CSPRNG as an option also.

**Comment by davidchambers** [comment]
Let's keep the discussion in one place: ramda/ramda#1677.
