### ISSUE TITLE
polymorphic functions cannot operate on "foreign" values

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#165]
#123 had one major unforeseen consequence.

To determine whether a value is a member of `Number`, say, sanctuary-def can ask `$.Number.test(x)`? To determine whether a value is a member of `a`, a type variable, sanctuary-def filters the set of types in the current environment to determine the set of types of which the value is a member, constraining `a`.

The problem is that Sanctuary provides a list of types to `$.create`, essentially stating _these are all the types that exist_. Sanctuary's polymorphic functions cannot operate on "unknown" types:

```javascript
S.I(document.body);
// ! TypeError: ‘I’ received [object HTMLBodyElement] as its first argument, but this value is not a member of any of the types in the environment:
//
//     - (Array ???)
//     - Boolean
//     ...
//     - ValidDate
//     - ValidNumber
```

```javascript
S.I({'@@type': 'my-package/MyType'});
// ! TypeError: ‘I’ received {"@@type": "my-package/MyType"} as its first argument, but this value is not a member of any of the types in the environment:
//
//     - (Array ???)
//     - Boolean
//     ...
//     - ValidDate
//     - ValidNumber
```

This is clearly a problem. What's more, [`S.type`][1] handles these "foreign" values:

```javascript
> S.type(document.body)
'HTMLBodyElement'

> S.type({'@@type': 'my-package/MyType'})
'my-package/MyType'
```

It's trivial to compare two type identifiers to determine whether two values are of the same type.

I believe the solution is as follows. When sanctuary-def determines that the value under interrogation is not a member of any of the types in the environment, it should not despair ([as it currently does][2]). Instead, it should calmly create a [`NullaryType`][3] and add it to the map:

```javascript
var typeIdentifier = $$type(value);
$typeVarMap[typeVarName] =
  [$.NullaryType(typeIdentifier, $$typeEq(typeIdentifier))];
```

It seems the fix should not be difficult. I hope to release a new version of sanctuary-def and a new version of Sanctuary this weekend.

Thank you @raqystyle for raising this issue on [Gitter][4].

[1]: https://github.com/plaid/sanctuary#type
[2]: https://github.com/plaid/sanctuary-def/blob/v0.4.0/index.js#L788-L790
[3]: https://github.com/plaid/sanctuary-def#nullarytype
[4]: https://gitter.im/plaid/sanctuary

**Comment by soroushjp** [comment]
I have also run into this same issue while working on a project with @davidchambers.

The proposed solution makes a lot of sense to me. Since the `@@type` property is the canonical source of truth about what the type of a given value is, this should work well.

Happy to test fix against the issue in our project once PR is opened to address this issue.

**Comment by davidchambers** [comment]
I have a sanctuary-def patch to address this issue (see [`dc-foreign`][1]). I'll open a pull request for it in the near future. :)


[1]: https://github.com/plaid/sanctuary-def/commits/dc-foreign
