### ISSUE TITLE
Switching from ramda.pipe to sanctuary.pipe causes errors when dealing with rx

### ISSUE THREAD

**Issue by krainboltgreene** [plaid/sanctuary#167]
So I have a cycle.js project, I use ramda's `pipe`, things work fine:

<img width="1407" alt="screen shot 2016-03-16 at 2 21 51 am" src="https://cloud.githubusercontent.com/assets/334809/13807348/fdaff986-eb1d-11e5-9d04-5d94f2b16571.png">

Today I wrote a [PR that switches this project to using sanctuary](https://github.com/lacqueristas/www/pull/1/files), but ran into some really head scratching issues:

<img width="1379" alt="screen shot 2016-03-16 at 2 22 09 am" src="https://cloud.githubusercontent.com/assets/334809/13807369/18b90cea-eb1e-11e5-8ea2-9eb180a17bd0.png">

The essence of this issue can be observed by modifying 

https://github.com/lacqueristas/www/pull/1/files#diff-895656aeaccff5d7c0f56a113ede9662L37

to look like this 

```
const dom$ = map((value) => console.log(value), storage$)
```

It now will console a strange Array: `[Object, 0, MapObservable]`. Before the change if you did this you would *only* get `Object`.

Since the *entire* pull request is simply importing from sanctuary and switching to the `pipe([])` api...I'm left wondering why this broke?

**Comment by krainboltgreene** [comment]
By the way, not knowing where this was *actually* happening (ie, what pipe) was a super pain, but I'm not sure what to do about that exactly.

**Comment by davidchambers** [comment]
First, I'm excited to see the reasons you listed in your pull request description. :)

Without looking closely at your code I can provide one guess as to what's going on. Consider:

```javascript
[1, 2, 3].map(R.pipe(R.inc));
// => [2, 3, 4]

[1, 2, 3].map(R.pipe(S.inc));
// ! ‘inc’ requires one argument; received three arguments

[1, 2, 3].map(S.pipe([S.inc]));
// ! ‘pipe’ requires two arguments; received four arguments
```

Ramda is forgiving of "extra" arguments; Sanctuary is not.

> By the way, not knowing where this was *actually* happening (ie, what pipe) was a super pain, but I'm not sure what to do about that exactly.

I suggest importing both `R.pipe` and `S.pipe`, then updating call sites one by one. After updating all the call sites (and resolving any issues) the `R.pipe` imports could be removed.

**Comment by krainboltgreene** [comment]
Wait, what? Why does Sanctuary behave this way? Why does ramda behave this way? Are you suggesting this isn't the "result":

``` javascript
[pipe(inc)(1), pipe(inc)(2), pipe(inc)(3)]
```

And that instead this is what's happening:

``` javascript
pipe([inc])(1)(2)(3)
```

Because that makes no sense.

**Comment by kedashoe** [comment]
Hi @krainboltgreene, I believe this was the implication:
```js
[pipe([inc])(1, 0, [1, 2, 3]), pipe([inc])(2, 1, [1, 2, 3]), pipe([inc])(3, 2, [1, 2, 3])]
```
Sanctuary's [pipe](http://sanctuary.js.org/#pipe) takes 2 arguments, but 4 are being passed in. I'm not familiar with Rx, but it does look like this is probably what is happening:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/select.md

**Comment by davidchambers** [comment]
@kedashoe beat me to the punch, but I'll post my comment anyway.

---

Let's take a step back.

```javascript
R.map(S.pipe([S.inc]), [1, 2, 3])

// is equivalent to...
[S.pipe([S.inc])(1), S.pipe([S.inc])(2), S.pipe([S.inc])(3)]

// which can be more simply expressed as...
[S.inc(1), S.inc(2), S.inc(3)]

// which of course evaluates to...
[2, 3, 4]
```

So far so good. `Array#map`, though, is not so well behaved.

```javascript
[1, 2, 3].map(S.pipe([S.inc]))

// is equivalent to...
[S.pipe([S.inc])(1, 0, [1, 2, 3]), S.pipe([S.inc])(2, 1, [1, 2, 3]), S.pipe([S.inc])(3, 2, [1, 2, 3])]
```

`S.pipe` thus receives four arguments: a list of functions, an element of the array, an index, and the array over which we're mapping.

**Comment by krainboltgreene** [comment]
Hoooooly crap haha, wow. I had no idea. Okay, so I guess my "solution" here is to use `R.unary`?

**Comment by davidchambers** [comment]
That's a workaround, yes. You could also mention this problem to the RxJS team. It would be great to have a ["lawful"][1] `map` method. :)


[1]: https://github.com/fantasyland/fantasy-land#functor

**Comment by krainboltgreene** [comment]
Thanks so much for helping!

**Comment by krainboltgreene** [comment]
For future me's out there, [Most.js doesn't suffer from this fate it looks like](https://github.com/cujojs/most/blob/master/docs/api.md#map).

**Comment by kedashoe** [comment]
Neither does [flyd](https://github.com/paldepind/flyd/blob/master/flyd.js#L182) :smile: (from ramda contributor @paldepind)

**Comment by svozza** [comment]
`Map` is a unary function in `Highland` too.
