### ISSUE TITLE
S.pluck?

### ISSUE THREAD

**Issue by svozza** [plaid/sanctuary#20]
This is really sheer laziness on my part but my code is littered with `R.map(S.get('key'), arr))`, it's an improvement on having to remember to do `R.reject(R.isNil, R.pluck('key', arr))` whenever I use `R.pluck` but it would be nice to have some sugar around such a common pattern.

**Comment by davidchambers** [comment]
`pluck` may be sugar, but sugar can be worthwhile. `R.pluck(x)` is sugar for `R.map(R.prop(x))`; `S.pluck(x)` could similarly be sugar for `R.map(S.get(x))`. The hitch is that Sanctuary doesn't currently depend on Ramda, though it's becoming clear that it should.

I'll put together a pull request to add Ramda as a dependency. Once that has been reviewed and merged, perhaps you'd like to open a pull request to add `S.pluck`. :)

On a different note, it's worth keeping in mind this distinction:

```javascript
> R.prop('a', {})
undefined
> R.prop('a', {a: undefined})
undefined
> S.get('a', {})
Nothing()
> S.get('a', {a: undefined})
Just(undefined)
```

**Comment by svozza** [comment]
Well I was planning on opening a PR that created the functionality from scratch,  or at least with no dependencies, but if you want to use Ramda I can  easily do that instead.

**Comment by davidchambers** [comment]
Ramda is now a dependency, so open a pull request to add `S.pluck` if you feel so inclined, @svozza. :)

**Comment by svozza** [comment]
Excellent. I'll definitely have time over the weekend.
