### ISSUE TITLE
Support ES6 Map Type

### ISSUE THREAD

**Issue by benperez** [plaid/sanctuary#24]
[Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) are a new feature of ES6 that could replace the de facto use of objects as dictionaries in JS.

Haskell has a [Data.Map](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/containers/Data-Map-Lazy.html#t:Map) module that has the following [API](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/containers/Data-Map-Lazy.html#v:lookup) for getting a value for a given key.
```haskell
lookup :: Ord k => k -> Map k a -> Maybe a 
```

This feels like a pretty natural fit for sanctuary and mimics the way we're using `S.get` in a lot of places currently. How would you feel about adding some functions that explicitly operate on ES6 Maps with a nice API using the Maybe type?

**Comment by davidchambers** [comment]
Currently we have:

    get :: String -> Object -> Maybe *
    gets :: [String] -> Object -> Maybe *

What do you have in mind? Perhaps:

    mapGet :: * -> Map -> Maybe *
    mapGets :: [*] -> Map -> Maybe *

**Comment by benperez** [comment]
The basics would be the following:
```haskell
insert :: k -> a -> Map k a -> Map k a 
delete :: k -> Map k a -> Map k a
lookup :: k -> Map k a -> Maybe a 
```
The `Data.Map.Lazy` API is pretty huge but I think there are a few natural directions to go from there. First would be convenience functions like `toList`, `fromList`, `keys`, and `elems`. From there it could be useful to define the [map](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/containers/Data-Map-Lazy.html#g:14) and [fold](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/containers/Data-Map-Lazy.html#g:15) families of functions and possibly `intersection`, `union`, and `difference`.

Advantages of adding this to Sanctuary:

1. A lookup API using Sanctuary's `Maybe` type feels like a very natural fit.
2. We could replace the somewhat hacky use of JavaScript objects as Maps (we can use non-string keys and readily access the size of a map).
3. There are a lot of transformations on Maps (or objects) that we could add to a Sanctuary Map type that are currently awkward to do in Ramda—a lot of times I find myself doing some variant of  `R.pipe(R.toPairs, someFunc, R.fromPairs)(someObject)` when I really want some kind transformation or aggregation directly over the Map itself.

**Comment by davidchambers** [comment]
This sounds very interesting indeed. A pull request to define `insert`, `delete`, and `lookup` would be useful at it would give us something concrete to discuss.

**Comment by davidchambers** [comment]
It appears likely that ramda/ramda#1056 will be updated and merged in the not too distant future, which means `S.get` and `S.gets` will one day work with Map objects. Thank you for triggering this sequence of events, @benperez!

**Comment by benperez** [comment]
:+1:
