### ISSUE TITLE
Ramda String Functions 

### ISSUE THREAD

**Issue by svozza** [plaid/sanctuary#39]
Working on #38 got me thinking about the other Ramda string functions that return a negative result that's not necessarily a `null` or `undefined`. For example, if you pass an index to `substringFrom` that's greater than the length of the string being operated on you just get back an empty string. Would it be useful to have a sanctified version that returns a Nothing in these sorts of cases?

**Comment by davidchambers** [comment]
Before considering string slice functions, let's decide whether a sanctified version of [`R.slice`][1] is a good idea. We could implement [`S.tail`][2] and [`S.init`][3] in terms of `S.slice`:

```javascript
S.tail = slice(1, Infinity);
S.init = slice(0, -1);
```

```javascript
> S.slice(2, 4, [])
Nothing()
> S.slice(2, 4, ['a', 'b', 'c', 'd', 'e'])
Just(['c', 'd'])
```

I'm not sure how `S.slice(2, 102, ['a', 'b', 'c', 'd', 'e'])` would evaluate.


[1]: http://ramdajs.com/docs/#slice
[2]: https://github.com/plaid/sanctuary#tail
[3]: https://github.com/plaid/sanctuary#init

**Comment by svozza** [comment]
I guess there's not much difference between `slice` when `toIndex > arr.length` and `tail` so I think it's justified in only returning the remaining elements of the array. I don't think it would be that useful to return what amounts to a sparse array with 96 `Nothing`s or `Just(undefined)`s.

**Comment by davidchambers** [comment]
I'm wondering how the following translates to the hypothetical `S.slice`:

```javascript
> S.tail([1, 2, 3])
Just([2, 3])
> S.tail([1, 2])
Just([2])
> S.tail([1])
Just([])
> S.tail([])
Nothing()
```

It seems `S.slice` should only return a Just if the array contains the *entire* range of indexes (otherwise it isn't well differentiated from [`R.slice`][1]):

```javascript
> S.slice(1, 1, ['a', 'b', 'c'])
Just([])
> S.slice(1, 2, ['a', 'b', 'c'])
Just(['b'])
> S.slice(1, 3, ['a', 'b', 'c'])
Just(['b', 'c'])
> S.slice(1, 4, ['a', 'b', 'c'])
Nothing()
```

This would guarantee that if `startIndex >= 0` and `endIndex >= 0` and `startIndex <= endIndex`, the resulting list will contain `endIndex - startIndex` elements.


[1]: http://ramdajs.com/docs/#slice

**Comment by svozza** [comment]
Ah okay, I see where you're coming from. Seems like that's the implementation favoured here:

https://wiki.haskell.org/99_questions/Solutions/18

And here:

https://hackage.haskell.org/package/repa-array-4.1.0.1/docs/src/Data-Repa-Array-Auto-Operator.html

```haskell
slice   :: Elem a => Int -> Int -> Array a -> Maybe (Array a)
slice from len arr
        | from >= 0, len >= 0
        , len  <= G.length arr - from
        = Just $ A.window from len arr

        | otherwise
        = Nothing
```

**Comment by davidchambers** [comment]
Thanks for investigating, @svozza. Let's add `S.slice` before deciding whether any string-specific functions are necessary.

**Comment by svozza** [comment]
Sounds good, I'll pick up this PR of you want.

**Comment by davidchambers** [comment]
Go for it! :)

**Comment by davidchambers** [comment]
We could define `S.take` and `S.drop`:

```javascript
> S.take(2, ['a', 'b', 'c'])
Just(['a', 'b'])
> S.take(3, ['a', 'b', 'c'])
Just(['a', 'b', 'c'])
> S.take(4, ['a', 'b', 'c'])
Nothing()
> S.drop(2, ['a', 'b', 'c'])
Just(['c'])
> S.drop(3, ['a', 'b', 'c'])
Just([])
> S.drop(4, ['a', 'b', 'c'])
Nothing()
```

ramda/ramda#1159 deprecates `R.substringTo` and `R.substringFrom`. We could define `S.take` and `S.drop` in terms of `S.slice` so they would also work with strings.

**Comment by svozza** [comment]
Yep, sounds good. I can work on this later on today.

**Comment by davidchambers** [comment]
We now have `S.slice`, `S.take`, and `S.drop`, all of which can operate on strings (in addition to `S.indexOf` and `S.lastIndexOf` which are similarly polymorphic).
