### ISSUE TITLE
Ramda Hard Dependency

### ISSUE THREAD

**Issue by jgrund** [plaid/sanctuary#40]
Sanctuary is very cool. 

However, what if a user wants to use sanctuary, but does not want the hard dependency on Ramda?

Is there a plan at some point to make this lib standalone?

**Comment by davidchambers** [comment]
Initially Sanctuary was a stand-alone library. Ramda was added as a dependency in #21. The reasons given in that pull request's description remain valid.

Although I'm not opposed to duplicating some of Ramda's internals, there are two features I'm unwilling to relinquish:

  - __Placeholder support__

    Since Sanctuary functions are curried by [`R.curry`][1] they support the [`R.__`][2] placeholder value. The current implementation of `R.curry` relies on an identity check to determine whether any given argument is the placeholder value.

    Sanctuary could duplicate [__curryN.js__][3] and replace the identity check with an equivalence check (the current value of `R.__` is `{ramda: 'placeholder'}`). In ramda/ramda#1052 @paldepind proposed an approach which would allow libraries to respect one another's placeholder values in a more general manner.

  - __Recursive string representations__

    The fact that `S.match(/(good)?bye/, 'bye').toString()` evaluates to `'Just([Just("bye"), Nothing()])'` is extremely useful. Without a useful `toString` method one must resort to logging the value itself and making sense of the output (`{ value: [ { value: 'bye' }, {} ] }` in this case).

    Duplicating [**_toString.js**][4] doesn't seem a good option, but if Ramda were to provide a `ramda-tostring` package Sanctuary could depend on it rather than `ramda`.

I'm curious that you're interested in using Sanctuary without Ramda. Are you writing front-end JavaScript and seeking to keep the file size of your dependencies under control, or are you using another library such as Underscore or lodash?


[1]: http://ramdajs.com/docs/#curry
[2]: http://ramdajs.com/docs/#__
[3]: https://github.com/ramda/ramda/blob/v0.14.0/src/curryN.js
[4]: https://github.com/ramda/ramda/blob/v0.14.0/src/internal/_toString.js

**Comment by paldepind** [comment]
> but if Ramda were to provide a ramda-tostring package Sanctuary could depend on it rather than ramda.

What about doing [something like this](https://github.com/paldepind/union-type-js/blob/master/union-type.js#L1)?

**Comment by davidchambers** [comment]
@paldepind, that's a good option for those using Browserify, CommonJS Everywhere, or a similar tool. :)

**Comment by paldepind** [comment]
And a browser build could be made as well. If you are not using Ramda then including the Ramda functions inside the built is what one wants?

**Comment by davidchambers** [comment]
> And a browser build could be made as well.

That's a good idea, if we decide to go down this path.

**Comment by svozza** [comment]
Maybe it's because I only work server-side but I don't really have an issue with a dependency on Ramda, it seems strange to me to be be duplicating work that's already been done there. And it seems like a lot of effort to modularise the dependencies down to the function level when Ramda minified is only 32kb.

**Comment by jgrund** [comment]
@davidchambers I am writing both server and client side JS, so file size is somewhat of a concern. 

More than that though, I work in an environment that is very sensitive to dependencies. Any new deps are heavily scrutinized.

I am in the process of removing lodash in favor of an in house functional lib. As such I was interested in your thoughts of making this dep free as it would be one less dependency I would not need to include in my project. 

In the end though, I think I am going to use a `safe` check function that will return a default result for arguments that don't meet it's criteria.

Thanks for your consideration. I'm not sure if other's want this for different reasons but if everyone is satisfied feel free to close.

**Comment by davidchambers** [comment]
ramda/ramda#1156 would make it possible for Sanctuary to provide its own :curry: function which respects `R.__` and other compatible placeholders. That said, Sanctuary makes heavy use of Ramda internally—and the source code is clearer as a result—so I don't foresee removing the Ramda dependency in the near future.
