### ISSUE TITLE
mapMaybe :: (a -> Maybe b) -> [a] -> [b]

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#73]
<https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Maybe.html#v:mapMaybe>:

> The `mapMaybe` function is a version of `map` which can throw out elements. In particular, the functional argument returns something of type `Maybe b`. If this is `Nothing`, no element is added on to the result list. If it is `Just b`, then `b` is included in the result list.

**Comment by tel** [comment]
I really like to call this filter, since it's just a small generalization of normal filter.

Unfortunately that'd be a bit of a breaking change.

**Comment by davidchambers** [comment]
> I really like to call this filter, since it's just a small generalization of normal filter.

Interesting idea. The fact that `mapMaybe` filters *while mapping* makes it significantly different from the typical `(a -> Boolean) -> [a] -> [a]` filter function in my eyes. Consider:

```javascript
> S.mapMaybe(S.head, ['foo', 'bar', 'baz'])
["f", "b", "b"]
```

> Unfortunately that'd be a bit of a breaking change.

In what respect? `S.filter` is not currently defined, though we do provide [`Maybe#filter`][1] for use with [`R.filter`][2], and having two quite different things named `filter` could cause confusion.


[1]: https://github.com/plaid/sanctuary#Maybe.prototype.filter
[2]: http://ramdajs.com/docs/#filter
