### ISSUE TITLE
reconsider Maybe#empty

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#74]
```javascript
> R.empty(S.Nothing())
Nothing()
> R.empty(S.Just([1, 2, 3]))
Nothing()
```

Should the latter give `Just([])` instead? [Monoids for Maybe][1] suggests that both approaches are valid. Which do you think is more useful, @joneshf?

[1]: https://byorgey.wordpress.com/2011/04/18/monoids-for-maybe/

**Comment by joneshf** [comment]
I think they're all equally useful. Can you defer the decision to the user? Also, wont the `Semigroup` have something to say about what the `Monoid` can be?

**Comment by davidchambers** [comment]
> Can you defer the decision to the user?

Could you elaborate? Currently `Maybe.prototype.empty` is essentially defined as `() => Nothing()`, so the user has no say in the matter.

> Also, wont the `Semigroup` have something to say about what the `Monoid` can be?

Good point. I don't think `Maybe#concat` would need to change, though, since both

```javascript
R.concat(S.Just([1, 2, 3]), S.Nothing())
```

and

```javascript
R.concat(S.Just([1, 2, 3]), S.Just([]))
```

evaluate to `Just([1, 2, 3])`, so we satisfy the [Monoid][1] identity laws either way.


[1]: https://github.com/fantasyland/fantasy-land#monoid

**Comment by davidchambers** [comment]
Consider the matter reconsidered.
