### ISSUE TITLE
create stand-alone package for def function

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#75]
This function could be used by other libraries. It would also enable wrappers for libraries (such as Ramda) which don't provide a descriptive error message when given a value of the wrong type.

**Comment by boxofrox** [comment]
As alluded to in gitter.im/ramda/ramda, I'm very interested in alternatives to debugging than with stack traces.  At the moment I get by with `trace`[1] and stack traces.  I don't yet conceive how `def` will work, but it sounds vaguely related to Meteor's `check` and React's `propTypes` which have saved me in past projects.

```js
// [1]
var R = require('ramda');
var trace = R.curry(function (tag, x) {
  console.log(tag, x);
  return x;
}
```

**Comment by davidchambers** [comment]
> I don't yet conceive how `def` will work

I'm sorry about the lack of detail in the issue description. An example would surely help!

```javascript
const R = require('ramda');
const def = require('sanctuary-def');

// inc :: Number -> Number
const inc = def('inc', [Number], R.inc);

R.inc('XXX');
// => "1XXX"

inc('XXX');
// ! TypeError: ‘inc’ requires a value of type Number as its first argument; received "XXX"
```

`def` takes three arguments: a name, a list of [type representatives][1], and a function to wrap (and :curry:). See Sanctuary's source code for more usage examples.


[1]: https://github.com/plaid/sanctuary#type-representatives

**Comment by davidchase** [comment]
A standalone library for creating methods with type definitions would be :+1:  I 1st saw this concept on your [envvar](https://github.com/plaid/envvar/blob/master/index.js#L15) and i liked the idea so i wrote one for my job... but my current verison just supports regular functions without currying so its pretty naive.

**Comment by davidchambers** [comment]
Thank you, @boxofrox and @davidchase, for chiming in. Now that there's interest in this functionality I'll prioritize this above some of the other Sanctuary-related tasks currently on my mind.
