### ISSUE TITLE
publish to Bower registry

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary#88]
As suggested by @ChetHarrison on Gitter.

1.  Add __bower.json__

2.  Run `bower register sanctuary git://github.com/plaid/sanctuary.git`

**Comment by davidchambers** [comment]
```console
$ bower info sanctuary
bower sanctuary#*               cached git://github.com/plaid/sanctuary.git#0.6.0
bower sanctuary#*             validate 0.6.0 against git://github.com/plaid/sanctuary.git#*

{
  name: 'sanctuary',
  homepage: 'https://github.com/plaid/sanctuary',
  version: '0.6.0'
}

Available versions:
  - 0.6.0
  - 0.5.0
  - 0.4.0
  - 0.3.0
  - 0.2.0
  - 0.1.0
You can request info for a specific version with 'bower info sanctuary#<version>'
```

**Comment by ChetHarrison** [comment]
Thanks!!!


On Sep 18, 2015, at 5:08 PM, David Chambers <notifications@github.com> wrote:

$ bower info sanctuary
bower sanctuary#*               cached git://github.com/plaid/sanctuary.git#0.6.0
bower sanctuary#*             validate 0.6.0 against git://github.com/plaid/sanctuary.git#*

{
  name: 'sanctuary',
  homepage: 'https://github.com/plaid/sanctuary',
  version: '0.6.0'
}

Available versions:
  - 0.6.0
  - 0.5.0
  - 0.4.0
  - 0.3.0
  - 0.2.0
  - 0.1.0
You can request info for a specific version with 'bower info sanctuary#<version>'
