### ISSUE TITLE
Add S.unfoldr

### ISSUE THREAD

**Issue by benperez** [plaid/sanctuary#89]
This has always felt awkward [in Ramda](http://ramdajs.com/docs/#unfold) since the supplied function returns `false` or an actual value. The [haskell version](http://hackage.haskell.org/package/base-4.8.1.0/docs/Data-List.html#v:unfoldr) uses maybe and is much more elegant.

```haskell
(b -> Maybe (a, b)) -> b -> [a] 
```

**Comment by davidchambers** [comment]
:+1:
